#!/usr/bin/env bash
# mindbender-hack -- run commands inside mindbender's environment
# > mindbender hack [COMMAND [ARG]...]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-05-10
set -eu

[ $# -gt 0 ] || set -- bash --norc -i

exec "$@"
