#!/usr/bin/env bash
# skbdo-hack -- run commands inside skbdo's environment
# > skbdo hack [COMMAND [ARG]...]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-05-10
set -eu

[ $# -gt 0 ] || set -- bash --norc -i

exec "$@"
