#!/usr/bin/env bash
# dashboard-report-template -- Manipulate report templates
# > dashboard-report-template ls
# > dashboard-report-template get NAME
# > dashboard-report-template put NAME <TEMPLATE_JSON
# > dashboard-report-template delete NAME
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-04-29
set -eu

DEEPDIVE_APP=$(find-deepdive-app)
export DEEPDIVE_APP

[[ $# -gt 0 ]] || usage "$0" "No verb given"
Command=$1; shift
case $Command in
    ls)
        ;;
    get|put|delete)
        [[ $# -gt 0 ]] || usage "$0" "No NAME given"
        TemplateName=$1; shift
        TemplateName=${TemplateName%/}
        ;;
    *)
        usage "$0" "get, put, or delete must be given"
esac

reportTemplateImportOrder=(
"$DEEPDIVE_APP"/report-templates
"$MINDBENDER_HOME"/etc/report-templates
)

# TODO speed up JSON generation
case $Command in
    ls) # list report templates in JSON array
        echo "["
        find "${reportTemplateImportOrder[@]}" \
            \( -name "README.md.in" \
            -o -name "report.sql.in" \
            \) -print |
        sed 's:^.*/report-templates/::; s:/[^/]*$::' |
        sort -u |
        while read template; do
            echo ","
            # TODO need to do complete JSON escaping
            printf '"%s"\n' "$template"
        done | tail -n +2
        echo "]"
        ;;

    get) # encode report template into a JSON object
        tmp=$(mktemp -d ${TMPDIR:-/tmp}/dashboard-report-template.XXXXXX)
        trap "rm -rf $tmp" EXIT
        export JSON_FILE=-  # to use report-values for constructing JSON

        # find the report-template
        for dir in "${reportTemplateImportOrder[@]}"; do
            reportTemplatePath="$dir/$TemplateName"
            [[ -d "$reportTemplatePath" ]] || continue

            # TODO It's probably a very good idea to implement this JSON construction in another language as this is already pretty slow.  A small obstacle would be interpreting the report.params files.
            # encode parameters by interpreting report.params
            required() {
                local name=$1; shift
                local desc=$1; shift
                JSON_FILE=$tmp/params.json report-values \
                    "$name=$(report-values \
                        inheritedFrom=$inheritedFrom \
                        isRequired=true \
                        description="$desc")"
            }
            optional() {
                local name=$1; shift
                local valueDefault=$1; shift
                local desc=$1; shift
                JSON_FILE=$tmp/params.json report-values \
                    "$name=$(report-values \
                        inheritedFrom=$inheritedFrom \
                        isRequired=false \
                        defaultValue="$valueDefault" \
                        description="$desc")"
            }
            echo '{}' >$tmp/params.json
            (
            list-breadcrumb-paths "$TemplateName" |
            while read path; do
                (
                path=${path%/}
                cd "$dir/$path"
                [[ -e report.params ]] || continue
                # record provenance of inherited parameters
                if [[ "$path" = "$TemplateName" ]]
                then inheritedFrom=null
                else inheritedFrom=$path
                fi
                # interpret report.params
                source report.params
                )
            done
            )
            JSON_FILE=$tmp/template.json report-values \
                params="$(cat $tmp/params.json)"

            cd "$reportTemplatePath"

            # encode markdownTemplate
            if [[ -e README.md.in ]]; then
                JSON_FILE=$tmp/template.json report-values \
                    markdownTemplate="$(cat README.md.in)"
            fi

            # encode sqlTemplate
            if [[ -e report.sql.in ]]; then
                JSON_FILE=$tmp/template.json report-values \
                    sqlTemplate="$(cat report.sql.in)"
            fi
            break
        done

        # finally, output the template JSON object
        cat $tmp/template.json
        ;;

    put) # decode report template from given JSON object
        reportTemplatePath="$DEEPDIVE_APP"/report-templates/"$TemplateName"
        mkdir -p "$reportTemplatePath"
        cd "$reportTemplatePath"

        # clean up existing artifacts before decoding
        rm -f report.sql.in

        # decode the input JSON object and create corresponding files
        coffee -e '
            fs = require "fs"
            _ = require "underscore"
            [jsonFile] = process.argv[4..]

            ## read and parse input report template object
            reportTemplate = JSON.parse fs.readFileSync jsonFile

            ## write files under the report template file
            # XXX string escaping is ugly and very convoluted, but is contained in the next line
            esc = (s) -> "'\''" + (
                    unless s? then ""
                    else (String s).replace /'\''/g, "'\''\\'\'\''"
                ) + "'\''"
            # shorthand for conditionally writing pieces of report template
            write = (fileName, content) ->
                if content?
                    fs.writeFileSync fileName, content
                    yes
            write "report.params", (
                if (_.size reportTemplate.params) > 0
                    for name,{isRequired,defaultValue,description,inheritedFrom} of reportTemplate.params when not inheritedFrom?
                        if isRequired
                            "required #{esc name} #{esc description}"
                        else
                            "optional #{esc name} #{esc defaultValue} #{esc description}"
            )?.join "\n"
            write "README.md.in", reportTemplate.markdownTemplate
            write "report.sql.in", reportTemplate.sqlTemplate
            # keep chart parameters
            write "report.chart",
                JSON.stringify reportTemplate.chart if reportTemplate.chart?
        ' /dev/stdin

        # clean up conflicting artifacts after decoding
        if [[ -e report.sql.in ]]; then
            # place the default report.sh when there's a report.sql.in
            cp -f "$MINDBENDER_HOME"/etc/report-sql-template.sh report.sh
        fi
        ;;

    delete) # delete given report template
        reportTemplatePath="$DEEPDIVE_APP"/report-templates/"$TemplateName"
        [[ -d "$reportTemplatePath" ]] ||
            error "$TemplateName: No deletable report template found"
        rm -rf "$reportTemplatePath"
        ;;
esac
