#!/usr/bin/env bash
# dashboard-snapshot-config -- Manipulate report templates
# > dashboard-snapshot-config ls
# > dashboard-snapshot-config get NAME
# > dashboard-snapshot-config put NAME <CONFIG_JSON
# > dashboard-snapshot-config delete NAME
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-05-01
set -eu

DEEPDIVE_APP=$(find-deepdive-app)
export DEEPDIVE_APP
cd "$DEEPDIVE_APP"

[[ $# -gt 0 ]] || usage "$0" "No verb given"
Command=$1; shift
case $Command in
    ls)
        ;;
    get|put|delete)
        [[ $# -gt 0 ]] || usage "$0" "No verb given"
        ConfigName=${1:-}; shift || usage
        ConfigFile=snapshot-"$ConfigName".conf
        ;;
    *)
        usage "$0" "ls, get, put, or delete must be given"
esac

case $Command in
    ls)
        echo "["
        for ConfigFile in snapshot-*.conf; do
            [[ -e "$ConfigFile" ]] || continue
            ConfigName=${ConfigFile#snapshot-}
            ConfigName=${ConfigName%.conf}
            echo ","
            # TODO handle JSON escapes correctly
            printf '"%s"\n' "$ConfigName"
        done | tail -n +2
        echo "]"
        ;;

    get) # encode snapshot configuration into a JSON object
        [[ -e "$ConfigFile" ]] || error "$ConfigName: No such snapshot configuration"
        export JSON_FILE=-  # to use report-values for constructing JSON

        # get ready to interpret the 
        report() {
            local name=$1; shift
            echo ","
            report-values \
                reportTemplate="$name" \
                params="$(report-values "$@")"
        }
        section() {
            : # ignored
        }
        echo "["
        (source "$ConfigFile") | tail -n +2
        echo "]"
        ;;

    put) # decode snapshot configuration from given JSON object
        coffee -e '
            fs = require "fs"
            _ = require "underscore"
            [jsonFile] = process.argv[4..]

            ## read and parse input report template object
            snapshotConfig = JSON.parse fs.readFileSync jsonFile

            ## write files under the report template file
            # XXX string escaping is ugly and very convoluted, but is contained in the next line
            esc = (s) -> "'\''" + (
                    unless s? then ""
                    else (String s).replace /'\''/g, "'\''\\'\'\''"
                ) + "'\''"
            for {reportTemplate, params} in snapshotConfig
                console.log "report #{esc reportTemplate}  #{(
                    for name,value of params
                        "#{esc name}=#{esc value}"
                ).join " "}"
        ' /dev/stdin >"$ConfigFile".tmp
        mv -f "$ConfigFile".tmp "$ConfigFile"
        ;;

    delete) # delete given snapshot configuration
        rm -f "$ConfigFile"
        ;;
esac
