#!/usr/bin/env bash
# find-deepdive-db-uri -- Find the database URI of the current DeepDive app
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-02-08
exec deepdive env bash -euc '
cd "$(find-deepdive-app)"
. load-db-driver.sh
echo "$DEEPDIVE_DB_URL"
'
