#!/usr/bin/env bash
# find-deepdive-db-uri -- Find the database URI of the current DeepDive app
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-02-08
set -eu

DEEPDIVE_APP=$(find-deepdive-app)
cd "$DEEPDIVE_APP"

if [[ application.conf -nt snapshot/.dburi ]]; then
    # extract DB URI from the DeepDive app
    mkdir -p snapshot
    eval-coffee-on-deepdive-app-conf '
        try
            jdbcUrl = appConf.deepdive?.db?.default?.url
            dbUri = jdbcUrl.replace /^jdbc:/i, ""
            console.log dbUri
        catch err
            console.error "Unable to recognize database configuration in your DeepDive app"
            process.exit 1
    ' >snapshot/.dburi
fi
cat snapshot/.dburi
