#!/usr/bin/env bash
# find-deepdive-db-uri -- Find the database URI of the current DeepDive app
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-02-08
set -eu

DEEPDIVE_APP=$(find-deepdive-app)

# TODO need a more reliable way to extract these from the DeepDive app
{
set +eu
. "$DEEPDIVE_APP"/env.sh
set -eu
} &>/dev/null  # ignore output

# produce a URI
if [[ -n "${PGHOST:-}" && -n "${DBNAME:-}" ]]; then
    echo "postgresql://${PGUSER:+$PGUSER@}$PGHOST${PGPORT:+:$PGPORT}/$DBNAME"
else
    error "Unable to recognize database configuration in your DeepDive app"
fi
