#!/usr/bin/env bash
# find-deepdive-app -- Find the path to root of the enclosing DeepDive app
# > find-deepdive-app [PATH_TO_START_SEARCH_FROM]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-02-08
exec "$(deepdive whereis installed util/find-deepdive-app)"
