#!/usr/bin/env bash
# mindbender-dashboard -- Launch Dashboard for DeepDive
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-02-09
set -eu

DEEPDIVE_APP=$(find-deepdive-app)
export DEEPDIVE_APP

exec mindbender-gui "$@"
