#!/usr/bin/env bash
# mindbender-snapshot -- Produce a snapshot of the current DeepDive app
# > mindbender snapshot [SNAPSHOT_CONFIG]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-02-09
set -eu

# find path to the DeepDive app based on the snapshot path
DEEPDIVE_APP=$(find-deepdive-app)
export DEEPDIVE_APP
cd "$DEEPDIVE_APP"

ConfigName=${1:-default}
[[ $# -eq 0 ]] || shift

# figure out snapshot configuration file name
if [[ -e "$ConfigName" ]]; then
    snapshotConfiguration=$ConfigName
else
    snapshotConfiguration="$DEEPDIVE_APP"/snapshot-"$ConfigName".conf
fi

if ! [[ -e "$snapshotConfiguration" ]]; then
    # install default snapshot configuration if not there
    # TODO derive one from application.conf instead of hard coded one
    cp -f "$MINDBENDER_HOME"/etc/snapshot-default.conf "$DEEPDIVE_APP"/
    error "Default dashboard snapshot configuration was installed to the DeepDive app $DEEPDIVE_APP" || true
    snapshotConfiguration="$DEEPDIVE_APP"/snapshot-default.conf
fi

# create a fresh snapshot directory
SnapshotDir=snapshot/$(date +%Y%m%d)
serial=1
while [[ -e "$SnapshotDir-$serial" ]]; do
    let ++serial
done
SnapshotDir="$SnapshotDir-$serial"
mkdir -p "$SnapshotDir"/files

# display the snapshot ID
echo "${SnapshotDir#snapshot/}"
# TODO maintain a symlink

# keep a copy of important deepdive artifacts
[[ -e snapshot-files ]] ||
    cp -f "$MINDBENDER_HOME"/etc/snapshot-files .
sed 's/#.*//' <snapshot-files | grep -v '^$' |
xargs -I{} -- cp -a {} "$SnapshotDir"/files/
# TODO avoid copying files more than once into snapshot and create symlink to a master copy instead

# produce reports for the snapshot
mindbender-produce-reports "$SnapshotDir" "$snapshotConfiguration"

# place a symlink to the latest snapshot
ln -sfnv "${SnapshotDir#snapshot/}" snapshot/LATEST
