#!/usr/bin/env bash
# run-sql -- Run given SQL against the current DeepDive app's database
# > run-sql QUERY [ARGS]
# 
# XXX DEPRECATED: Using `deepdive sql` command directly is strongly recommended!
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-02-08
exec deepdive sql eval "$@"
