#!/usr/bin/env bash
# run-sql -- Run given SQL against the current DeepDive app's database
# > run-sql QUERY [ARGS]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-02-08
set -eu

[[ $# -gt 0 ]] || usage "$0" "Missing QUERY"

Query=$1; shift

dbURI=$(find-deepdive-db-uri)
case $dbURI in
    postgresql://*)
        psql "$dbURI" -c "COPY (
            $Query
        ) TO STDOUT $*"
        ;;

    *)
        error "$dbURI: DeepDive uses a database unsupported by Mindbender"
esac
